import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { answerDialog } from "@/shared/ui/dialogTest";
import RoleGroupLinks from "./RoleGroupLinks";
import type { RoleGroupCandidate, RoleGroupLink } from "./contextApi";
const api = vi.hoisted(() => ({ roleGroupLinks: vi.fn(), roleGroupCandidates: vi.fn(), linkRoleGroup: vi.fn(), unlinkRoleGroup: vi.fn() }));
vi.mock("./contextApi", async (original) => ({ ...await original<typeof import("./contextApi")>(), ...api }));
vi.mock("@/features/social/GroupShell", () => ({ default: ({ linkedGroup }: { linkedGroup: { onAccessLost: () => void } }) => <div>비공개 상세<button onClick={linkedGroup.onAccessLost}>권한 상실</button></div> }));
vi.mock("./RolePartyPanels", () => ({ default: () => <div>기존 역할 소모임 상세</div> }));
const group: RoleGroupCandidate = { groupType: "GUILD", groupId: 7, name: "내 비공개 길드", memberRole: "MEMBER" };
const link: RoleGroupLink = { linkId: 21, roleId: 1, groupType: "GUILD", groupId: 7, access: "AVAILABLE", group };
const page = <T,>(contents: T[]) => ({ contents, page: 0, size: 20, totalElements: contents.length, totalPages: 1 });
const props = { roleId: 1, roleName: "학습 역할", roleStatus: "ACTIVE", playerId: 39, createRequest: 0, reentryRequest: 0, onBack: vi.fn() };
beforeEach(() => { vi.resetAllMocks(); api.roleGroupLinks.mockResolvedValue(page([link])); api.roleGroupCandidates.mockResolvedValue(page([group])); api.linkRoleGroup.mockResolvedValue(link); api.unlinkRoleGroup.mockResolvedValue(undefined); });
it("lists first, selects existing detail and clears private title/detail on access loss while retaining unlink", async () => {
  render(<RoleGroupLinks {...props} />);
  expect(screen.queryByLabelText("모임 종류")).not.toBeInTheDocument();
  fireEvent.click(await screen.findByRole("button", { name: /내 비공개 길드/ }));
  expect(screen.getByText("비공개 상세")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "권한 상실" }));
  expect(screen.queryByText("비공개 상세")).not.toBeInTheDocument();
  expect(screen.queryByRole("button", { name: /내 비공개 길드/ })).not.toBeInTheDocument();
  fireEvent.keyDown(screen.getByRole("button", { name: /접근 불가/ }), { key: "F10", shiftKey: true });
  fireEvent.click(screen.getByRole("button", { name: "연결 해제" }));
  await answerDialog();
  await waitFor(() => expect(api.unlinkRoleGroup).toHaveBeenCalledWith(1, 21));
});
it("uses typed active-member candidates in the same slot and never repeats POST after failed GET", async () => {
  api.roleGroupLinks.mockRejectedValue(new Error("refresh offline"));
  render(<RoleGroupLinks {...props} createRequest={1} />);
  const node = document.querySelector('[data-stage-key="role-group-links"]');
  fireEvent.change(screen.getByLabelText("모임 종류"), { target: { value: "ROLE_PARTY" } });
  await waitFor(() => expect(api.roleGroupCandidates).toHaveBeenLastCalledWith(1, "ROLE_PARTY", 0, ""));
  fireEvent.click(await screen.findByRole("button", { name: /내 비공개 길드.*이 역할에서 보기/ }));
  expect(await screen.findByRole("alert")).toHaveTextContent("refresh offline");
  expect(document.querySelector('[data-stage-key="role-group-links"]')).toBe(node);
  expect(screen.queryByLabelText("모임 종류")).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: "다시 조회" }));
  await waitFor(() => expect(api.roleGroupLinks).toHaveBeenCalledTimes(2));
  expect(api.linkRoleGroup).toHaveBeenCalledTimes(1);
  expect(api.linkRoleGroup).toHaveBeenCalledWith(1, group);
});
it("deduplicates stable typed IDs, resets children on reentry, and retains the parent slot", async () => {
  api.roleGroupLinks.mockResolvedValue(page([link, link, { ...link, linkId: 22, groupType: "PARTY", group: { ...group, groupType: "PARTY", name: "같은 번호 파티" } }]));
  const view = render(<RoleGroupLinks {...props} />);
  expect(await screen.findAllByRole("button", { name: /내 비공개 길드/ })).toHaveLength(1);
  expect(screen.getByRole("button", { name: /같은 번호 파티/ })).toBeInTheDocument();
  const panel = document.querySelector('[data-stage-key="role-group-links"]');
  fireEvent.click(screen.getByRole("button", { name: /내 비공개 길드/ }));
  view.rerender(<RoleGroupLinks {...props} reentryRequest={1} />);
  expect(screen.queryByText("비공개 상세")).not.toBeInTheDocument();
  expect(document.querySelector('[data-stage-key="role-group-links"]')).toBe(panel);
});
it("ignores late candidate results after a type change", async () => {
  let resolve!: (value: ReturnType<typeof page<RoleGroupCandidate>>) => void;
  api.roleGroupCandidates.mockReturnValueOnce(new Promise((done) => { resolve = done; })).mockResolvedValueOnce(page([{ ...group, groupType: "PARTY", name: "현재 후보" }]));
  render(<RoleGroupLinks {...props} createRequest={1} />);
  fireEvent.change(screen.getByLabelText("모임 종류"), { target: { value: "PARTY" } });
  await screen.findByRole("button", { name: /현재 후보/ });
  await act(async () => resolve(page([group])));
  expect(screen.queryByRole("button", { name: /내 비공개 길드/ })).not.toBeInTheDocument();
});
