"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { PersonDetail, RoleEventDetail, RoleEventInput } from "@/shared/api/types";
import { ApiError } from "@/shared/api/client";
import { useMediaQuery } from "@/shared/hooks/useMediaQuery";
import { requestStageFocus } from "@/shared/hooks/useStageCamera";
import CreateSlot from "@/shared/ui/CreateSlot";
import PanelStage from "@/shared/ui/PanelStage";
import { useSaoConfirm } from "@/shared/ui/useSaoConfirm";
import { BackButton, PanelFrame } from "@/widgets/right-panels/ui/PanelFrame";
import { RecordRow } from "./RecordRow";
import { addRoleEventParticipantApi, cancelRoleEventApi, completeRoleEventApi, createRoleEventApi, getRoleEventApi, listPersonsApi, removeRoleEventParticipantApi, updateRoleEventApi } from "./api";
import GuildEventPanels from "@/features/social/GuildEventPanels";
import GroupActivityPanels from "@/features/social/GroupActivityPanels";
import { currentMonth, roleSchedule, scheduleKey, type ScheduleRow, type ScheduleSource, type ScheduleStatus } from "./scheduleApi";

type Mode = "list" | "create" | "detail" | "edit";
const localDate = (value: string | null) => value ? new Date(value).toLocaleString("sv-SE").replace(" ", "T").slice(0, 16) : "";
const instant = (value: FormDataEntryValue | null) => value ? new Date(String(value)).toISOString() : null;
const message = (error: unknown, fallback: string) => error instanceof ApiError && error.code === "ROL-403-EVENT-COMMAND-GATED" ? "현재 서버에서 일정 변경이 허용되지 않습니다." : error instanceof Error ? error.message : fallback;
const statusName = { PLANNED: "예정", COMPLETED: "완료", CANCELED: "취소" };
const displayTime = (row: ScheduleRow) => !row.startsAt && !row.endsAt ? "시간 미정" : row.startsAt && row.endsAt && row.startsAt !== row.endsAt ? `${new Date(row.startsAt).toLocaleString("ko-KR")} ~ ${new Date(row.endsAt).toLocaleString("ko-KR")}` : `${row.startsAt ? "시작" : "종료"} ${new Date(row.startsAt ?? row.endsAt!).toLocaleString("ko-KR")}`;

export default function RoleEventPanels({ roleId, roleName, roleStatus, createRequest, reentryRequest, onBack }: { roleId: number; roleName: string; roleStatus: string; createRequest: number; reentryRequest: number; onBack: () => void }) {
  const { confirm, dialog } = useSaoConfirm();
  const compact = useMediaQuery("(max-width: 1199px)");
  const [schedule, setSchedule] = useState<Awaited<ReturnType<typeof roleSchedule>> | null>(null), [listError, setListError] = useState<string | null>(null), [listLoading, setListLoading] = useState(true);
  const [month, setMonth] = useState(currentMonth), [source, setSource] = useState<ScheduleSource>("ALL"), [status, setStatus] = useState<ScheduleStatus>("PLANNED"), [unscheduled, setUnscheduled] = useState(false), [page, setPage] = useState(0);
  const [mode, setMode] = useState<Mode>("list"), [selectedId, setSelectedId] = useState<number | null>(null), [detail, setDetail] = useState<RoleEventDetail | null>(null);
  const [selectedGuild, setSelectedGuild] = useState<ScheduleRow | null>(null);
  const [selectedActivity, setSelectedActivity] = useState<ScheduleRow | null>(null);
  const [detailError, setDetailError] = useState<string | null>(null), [loading, setLoading] = useState(false), [pending, setPending] = useState(false);
  const [persons, setPersons] = useState<PersonDetail[]>([]), [participantType, setParticipantType] = useState<"PERSON" | "SERVICE_USER">("PERSON");
  const listSeq = useRef(0), detailSeq = useRef(0), busy = useRef(false);
  const load = useCallback(async () => { const seq = ++listSeq.current; setListLoading(true); setListError(null); setSchedule(null); try { const next = await roleSchedule(roleId, { month, unscheduled, source, status, page }); if (seq === listSeq.current) setSchedule(next); } catch (error) { if (seq === listSeq.current) setListError(error instanceof Error ? error.message : "일정을 불러오지 못했습니다."); } finally { if (seq === listSeq.current) setListLoading(false); } }, [roleId, month, unscheduled, source, status, page]);
  useEffect(() => { const listCounter = listSeq, detailCounter = detailSeq; void load(); return () => { listCounter.current++; detailCounter.current++; }; }, [load, reentryRequest]);
  useEffect(() => { if (createRequest || reentryRequest) { detailSeq.current++; setMode(createRequest && roleStatus === "ACTIVE" ? "create" : "list"); setDetail(null); setSelectedId(null); setSelectedGuild(null); setSelectedActivity(null); setDetailError(null); } }, [createRequest, reentryRequest, roleStatus]);
  useEffect(() => { const refresh = () => { detailSeq.current++; setSelectedId(null); setSelectedGuild(null); setSelectedActivity(null); setDetail(null); setMode("list"); void load(); }; window.addEventListener("focus", refresh); return () => window.removeEventListener("focus", refresh); }, [load]);
  useEffect(() => { void listPersonsApi().then(setPersons).catch(() => setPersons([])); }, []);
  const close = () => { detailSeq.current++; setMode("list"); setDetail(null); setSelectedId(null); setSelectedGuild(null); setSelectedActivity(null); setDetailError(null); requestStageFocus("role-detail", "back"); };
  const select = async (id: number, nextMode: Mode = "detail") => { const seq = ++detailSeq.current; setMode(nextMode); setSelectedGuild(null); setSelectedActivity(null); setSelectedId(id); setDetail(null); setDetailError(null); setLoading(true); try { const next = await getRoleEventApi(roleId, id); if (seq === detailSeq.current) setDetail(next); } catch (error) { if (seq === detailSeq.current) setDetailError(error instanceof Error ? error.message : "일정 상세를 불러오지 못했습니다."); } finally { if (seq === detailSeq.current) setLoading(false); } };
  const selectGuild = (row: ScheduleRow) => { detailSeq.current++; setSelectedId(null); setSelectedActivity(null); setDetail(null); setDetailError(null); setSelectedGuild(row); setMode("detail"); };
  const selectActivity = (row: ScheduleRow) => { detailSeq.current++; setSelectedId(null); setSelectedGuild(null); setDetail(null); setDetailError(null); setSelectedActivity(row); setMode("detail"); };
  const save = async (event: React.SubmitEvent<HTMLFormElement>) => {
    event.preventDefault(); if (busy.current) return;
    const form = new FormData(event.currentTarget);
    const body: RoleEventInput = { title: String(form.get("title") ?? "").trim(), description: String(form.get("description") ?? "").trim() || null, startsAt: instant(form.get("startsAt")), endsAt: instant(form.get("endsAt")) };
    if (roleStatus !== "ACTIVE" || !body.title || body.title.length > 120 || body.description && body.description.length > 1000 || body.startsAt && body.endsAt && body.startsAt > body.endsAt) { setDetailError("활성 역할인지, 제목·설명 길이와 시작·종료 시간을 확인해주세요."); return; }
    const seq = detailSeq.current;
    busy.current = true; setPending(true); setDetailError(null);
    try { const saved = mode === "edit" && selectedId !== null ? await updateRoleEventApi(roleId, selectedId, body) : await createRoleEventApi(roleId, body); await load(); if (seq === detailSeq.current) await select(saved.id); }
    catch (error) { if (seq === detailSeq.current) setDetailError(message(error, "일정을 저장하지 못했습니다.")); }
    finally { busy.current = false; setPending(false); }
  };
  const transition = async (action: "complete" | "cancel", id: number) => {
    if (busy.current) return;
    const seq = detailSeq.current;
    if (!await confirm(`이 일정을 ${action === "complete" ? "완료" : "취소"}할까요?`) || busy.current || seq !== detailSeq.current) return;
    busy.current = true; setPending(true); setDetailError(null);
    try { await (action === "complete" ? completeRoleEventApi(roleId, id) : cancelRoleEventApi(roleId, id)); await load(); if (seq === detailSeq.current && selectedId === id) await select(id); }
    catch (error) { if (seq === detailSeq.current) setDetailError(message(error, "상태를 변경하지 못했습니다.")); }
    finally { busy.current = false; setPending(false); }
  };
  const addParticipant = async (event: React.SubmitEvent<HTMLFormElement>) => { event.preventDefault(); if (!detail || busy.current) return; const form = new FormData(event.currentTarget); const participantId = Number(form.get("participantId")); if (!Number.isInteger(participantId) || participantId < 1) { setDetailError("참가자 ID를 확인해주세요."); return; } busy.current = true; setPending(true); setDetailError(null); try { await addRoleEventParticipantApi(roleId, detail.id, { participantType, participantId }); await select(detail.id); } catch (error) { setDetailError(message(error, "참가자를 추가하지 못했습니다.")); } finally { busy.current = false; setPending(false); } };
  const removeParticipant = async (linkId: number) => { if (!detail || busy.current || !await confirm("이 일정에서 참가자를 제외할까요?")) return; busy.current = true; setPending(true); setDetailError(null); try { await removeRoleEventParticipantApi(roleId, detail.id, linkId); await select(detail.id); } catch (error) { setDetailError(message(error, "참가자를 제외하지 못했습니다.")); } finally { busy.current = false; setPending(false); } };
  const form = (record?: RoleEventDetail) => <form key={record?.id ?? "new"} className="lag-role-form" onSubmit={(event) => void save(event)}><label>제목<input className="lag-role-control" name="title" required maxLength={120} autoFocus defaultValue={record?.title ?? ""} /></label><label>설명<textarea className="lag-role-control" name="description" maxLength={1000} rows={3} defaultValue={record?.description ?? ""} /></label><label>시작<input className="lag-role-control" name="startsAt" type="datetime-local" min="1000-01-01T00:00" defaultValue={localDate(record?.startsAt ?? null)} /></label><label>종료<input className="lag-role-control" name="endsAt" type="datetime-local" min="1000-01-01T00:00" defaultValue={localDate(record?.endsAt ?? null)} /></label>{detailError ? <p role="alert">{detailError}</p> : null}<button type="submit" className="lag-role-action" disabled={pending}>{pending ? "저장 중…" : "일정 저장"}</button></form>;
  return <div className="lag-panel-rail lag-role-events">{dialog}
    <PanelStage stageKey="role-detail" parentStageKey="role-summary" instant inactive={compact && (selectedId !== null || selectedGuild !== null || selectedActivity !== null)}><PanelFrame title={mode === "create" ? "새 일정" : `${roleName} · 일정`} backButton={<BackButton label={mode === "create" ? "일정 목록으로" : `역할 ${roleName}로`} onClick={mode === "create" ? close : onBack} />}>
      <CreateSlot creating={mode === "create"} showCancel={false} pending={pending} onClose={close} list={<div className="lag-role-detail">
        <div className="lag-schedule-filters"><label>기간<input className="lag-role-control" type="month" min="1000-01" max="9999-12" value={month} disabled={unscheduled} onChange={(event) => { close(); setMonth(event.target.value); setPage(0); }} /></label><button type="button" className="lag-role-button" aria-pressed={unscheduled} onClick={() => { close(); setUnscheduled(!unscheduled); setSource("PERSONAL"); setPage(0); }}>{unscheduled ? "월별 일정 보기" : "시간 미정 보기"}</button><label>출처<select className="lag-role-control" value={unscheduled ? "PERSONAL" : source} disabled={unscheduled} onChange={(event) => { close(); setSource(event.target.value as ScheduleSource); setPage(0); }}><option value="ALL">전체</option><option value="PERSONAL">개인 일정</option><option value="GUILD">길드 행사</option><option value="PARTY">파티 활동</option><option value="ROLE_PARTY">소모임 활동</option><option value="SHARED">모든 공유 일정</option><option value="PARTICIPATING">내가 참가한 공유 일정</option></select></label><label>상태<select className="lag-role-control" value={status} onChange={(event) => { close(); setStatus(event.target.value as ScheduleStatus); setPage(0); }}><option value="PLANNED">예정</option><option value="ALL">전체 상태</option><option value="COMPLETED">완료</option><option value="CANCELED">취소</option></select></label></div>
        {listLoading ? <p role="status">일정을 불러오는 중…</p> : null}{listError ? <p role="alert">{listError} <button type="button" className="lag-role-button" onClick={() => void load()}>다시 조회</button></p> : null}{mode === "list" && detailError ? <p role="alert">{detailError}</p> : null}{!listLoading && !listError && !schedule?.contents.length ? <p>{unscheduled ? "시간 미정 개인 일정이 없습니다." : "이 기간의 일정이 없습니다."}</p> : null}
        {schedule?.contents.map((item) => <div key={scheduleKey(item)} data-event-key={scheduleKey(item)}><RecordRow title={item.title} subtitle={`${displayTime(item)} · ${item.sourceType === "ROLE_EVENT" ? "개인 일정" : item.sourceType === "GUILD_EVENT" ? item.guildName ?? "길드 행사" : item.groupName ?? (item.sourceType === "PARTY_ACTIVITY" ? "파티 활동" : "소모임 활동")} · ${statusName[item.status]}${item.sourceType !== "ROLE_EVENT" ? item.myRsvp ? " · 내가 참가함" : " · 미참가" : ""}`} selected={item.sourceType === "ROLE_EVENT" ? selectedId === item.sourceId : item.sourceType === "GUILD_EVENT" ? selectedGuild?.sourceId === item.sourceId && selectedGuild.guildId === item.guildId : selectedActivity?.sourceType === item.sourceType && selectedActivity.sourceId === item.sourceId} disabled={pending} onSelect={() => item.sourceType === "ROLE_EVENT" ? void select(item.sourceId) : item.sourceType === "GUILD_EVENT" ? selectGuild(item) : selectActivity(item)} onEdit={item.sourceType === "ROLE_EVENT" && item.status === "PLANNED" && roleStatus === "ACTIVE" ? () => void select(item.sourceId, "edit") : undefined} onArchive={item.sourceType === "ROLE_EVENT" && item.status === "PLANNED" && roleStatus === "ACTIVE" ? () => void transition("cancel", item.sourceId) : undefined} archiveLabel="일정 취소" /></div>)}
        <div className="lag-connection-pagination"><button type="button" className="lag-role-button" disabled={listLoading || page === 0} onClick={() => { close(); setPage(page - 1); }}>이전</button><span>{page + 1} / {Math.max(1, schedule?.totalPages ?? 0)}</span><button type="button" className="lag-role-button" disabled={listLoading || !schedule || page >= 1000 || page + 1 >= schedule.totalPages} onClick={() => { close(); setPage(page + 1); }}>다음</button></div>
      </div>}>{form()}</CreateSlot>
    </PanelFrame></PanelStage>
    {(mode === "detail" || mode === "edit") && selectedId !== null ? <PanelStage stageKey="role-event-detail" parentStageKey="role-detail" instant><PanelFrame title={mode === "edit" ? "일정 수정" : "일정 상세"} backButton={<BackButton label={mode === "edit" ? "일정 상세로" : "일정 목록으로"} onClick={mode === "edit" ? () => { setMode("detail"); setDetailError(null); } : close} />}>
      {loading ? <p role="status">일정 상세를 불러오는 중…</p> : null}{detailError && !detail ? <p role="alert">{detailError} <button type="button" onClick={() => void select(selectedId, mode)}>다시 조회</button></p> : null}
      {detail && mode === "edit" ? form(detail) : detail ? <article className="lag-role-detail"><h4>{detail.title}</h4><p>{detail.description || "설명 없음"}</p><dl><div className="lag-role-data-row"><dt>상태</dt><dd>{detail.status === "PLANNED" ? "계획" : detail.status === "COMPLETED" ? "완료" : "취소"}</dd></div><div className="lag-role-data-row"><dt>시작</dt><dd>{detail.startsAt ? new Date(detail.startsAt).toLocaleString("ko-KR") : "미등록"}</dd></div><div className="lag-role-data-row"><dt>종료</dt><dd>{detail.endsAt ? new Date(detail.endsAt).toLocaleString("ko-KR") : "미등록"}</dd></div></dl>
        {detailError ? <p role="alert">{detailError}</p> : null}
        {roleStatus === "ACTIVE" && detail.status === "PLANNED" ? <div className="lag-role-actions"><button type="button" className="lag-role-action" disabled={pending} onClick={() => void transition("complete", detail.id)}>완료</button></div> : null}
        <h5 className="lag-role-subheading">참가자</h5><p>개인 일정 참조이며 소모임 가입이나 상대방 공유 동의와 무관합니다.</p>{detail.participants.length ? detail.participants.map((person) => <div className="lag-group-member" key={person.participantLinkId}><span>{person.participantType === "PERSON" ? "개인 인물" : "서비스 사용자"} #{person.participantId}</span>{roleStatus === "ACTIVE" && detail.status === "PLANNED" ? <button type="button" className="lag-role-button" disabled={pending} onClick={() => void removeParticipant(person.participantLinkId)}>참가자 제외</button> : null}</div>) : <p>참가자가 없습니다.</p>}
        {roleStatus === "ACTIVE" && detail.status === "PLANNED" ? <form className="lag-role-form" onSubmit={(event) => void addParticipant(event)}><label>참가자 종류<select className="lag-role-control" value={participantType} onChange={(event) => setParticipantType(event.target.value as typeof participantType)}><option value="PERSON">내 인물 기록</option><option value="SERVICE_USER">서비스 사용자</option></select></label>{participantType === "PERSON" ? <label>내 인물<select className="lag-role-control" name="participantId" required defaultValue=""><option value="" disabled>인물 선택</option>{persons.filter((person) => person.status === "ACTIVE").map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label> : <label>서비스 사용자 ID<input className="lag-role-control" name="participantId" type="number" min="1" required /></label>}<button type="submit" className="lag-role-button" disabled={pending || participantType === "PERSON" && !persons.some((person) => person.status === "ACTIVE")}>참가자 추가</button></form> : null}
      </article> : null}
    </PanelFrame></PanelStage> : null}
    {selectedActivity?.groupId != null ? <GroupActivityPanels key={scheduleKey(selectedActivity)} groupType={selectedActivity.sourceType === "PARTY_ACTIVITY" ? "PARTY" : "ROLE_PARTY"} groupId={selectedActivity.groupId} selectedActivityId={selectedActivity.sourceId} detailOnly parentStageKey="role-detail" onBack={close} onChanged={() => void load()} onAccessLost={() => { close(); setSchedule(null); void load(); }} /> : null}
    {selectedGuild?.guildId != null ? <GuildEventPanels key={scheduleKey(selectedGuild)} guildId={selectedGuild.guildId} selectedEventId={selectedGuild.sourceId} detailOnly creating={false} onBack={close} onChanged={() => void load()} onAccessLost={() => { close(); setSchedule(null); void load(); }} /> : null}
  </div>;
}
